name: Deploy

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9.1.4

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Build applications
        run: pnpm build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/ecommerce-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/ecommerce-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Add your deployment steps here (e.g., deploy to K8s, update docker-compose on server, etc.)
      - name: Deploy to server
        run: |
          echo "Add your deployment commands here"
          # Example: ssh to server and pull new images, restart services
          # ssh user@server "cd /app && docker-compose pull && docker-compose up -d"
